#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.0.3 effective-5.10 (swiftlang-6.0.3.1.10 clang-1600.0.30.1)
#ifndef SDKCA_SWIFT_H
#define SDKCA_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="SDKCA",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)
@class NSString;

SWIFT_CLASS("_TtC5SDKCA15ConfirmSignObjC")
@interface ConfirmSignObjC : NSObject
@property (nonatomic, readonly, strong) NSString * _Nonnull error_code;
@property (nonatomic, readonly, strong) NSString * _Nonnull error_message;
- (nonnull instancetype)initWithError_code:(NSString * _Nonnull)error_code error_message:(NSString * _Nonnull)error_message OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class InitializeResponseObjC;
@class NSError;
@class SessionResponseObjC;
@class RegisterDeviceObjC;
@class ListCertsObjC;
@class VerifyCertObjC;
@class ListSignObjC;
@class InitAuthorizeObjC;
@class ListAuthorizeObjC;
@class RegisterAuthorizeObjC;

SWIFT_CLASS_NAMED("EasyCAObjectCSDKImp")
@interface EasyCAObjectCSDKImp : NSObject
- (nonnull instancetype)initWithIsProd:(BOOL)isProd OBJC_DESIGNATED_INITIALIZER;
- (void)initializeWithLicenseCode:(NSString * _Nonnull)licenseCode completion:(void (^ _Nonnull)(InitializeResponseObjC * _Nullable, NSError * _Nullable))completion;
- (void)openSessionWithUser:(NSString * _Nonnull)user password:(NSString * _Nonnull)password completion:(void (^ _Nonnull)(SessionResponseObjC * _Nullable, NSError * _Nullable))completion;
- (void)registerDeviceWithPin:(NSString * _Nonnull)pin recoveryCode:(NSString * _Nonnull)recoveryCode fcmToken:(NSString * _Nonnull)fcmToken completion:(void (^ _Nonnull)(RegisterDeviceObjC * _Nullable, NSError * _Nullable))completion;
- (void)listCertsWithPageSize:(NSInteger)pageSize pageIndex:(NSInteger)pageIndex completion:(void (^ _Nonnull)(ListCertsObjC * _Nullable, NSError * _Nullable))completion;
- (void)verifyCertWithSerial:(NSString * _Nonnull)serial completion:(void (^ _Nonnull)(VerifyCertObjC * _Nullable, NSError * _Nullable))completion;
- (void)listSignRequestWithPageSize:(NSInteger)pageSize pageIndex:(NSInteger)pageIndex completion:(void (^ _Nonnull)(ListSignObjC * _Nullable, NSError * _Nullable))completion;
- (void)confirmSignWithUserPin:(NSString * _Nonnull)userPin authData:(NSString * _Nonnull)authData authId:(NSString * _Nonnull)authId signRequestId:(NSString * _Nonnull)signRequestId confirm:(BOOL)confirm completion:(void (^ _Nonnull)(ConfirmSignObjC * _Nullable, NSError * _Nullable))completion;
- (void)initAuthorizeWithSerial:(NSString * _Nonnull)serial quantity:(NSInteger)quantity time:(NSInteger)time message:(NSString * _Nonnull)message completion:(void (^ _Nonnull)(InitAuthorizeObjC * _Nullable, NSError * _Nullable))completion SWIFT_METHOD_FAMILY(none);
- (void)listAuthorizeWithPageSize:(NSInteger)pageSize pageNumber:(NSInteger)pageNumber status:(NSString * _Nonnull)status completion:(void (^ _Nonnull)(ListAuthorizeObjC * _Nullable, NSError * _Nullable))completion;
- (void)registerAuthorizeWithId:(NSString * _Nonnull)authorizeRequestId authId:(NSString * _Nonnull)authId authData:(NSString * _Nonnull)authData pin:(NSString * _Nonnull)pin confirm:(BOOL)confirm completion:(void (^ _Nonnull)(RegisterAuthorizeObjC * _Nullable, NSError * _Nullable))completion;
- (void)openSessionIdWithUser:(NSString * _Nonnull)user accessToken:(NSString * _Nonnull)accessToken completion:(void (^ _Nonnull)(SessionResponseObjC * _Nullable, NSError * _Nullable))completion;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class InitAuthorizeResponseObjC;

SWIFT_CLASS_NAMED("InitAuthorizeObjC")
@interface InitAuthorizeObjC : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull error_code;
@property (nonatomic, readonly, copy) NSString * _Nonnull error_message;
@property (nonatomic, readonly, strong) InitAuthorizeResponseObjC * _Nullable initAuthorizeResponse;
- (InitAuthorizeResponseObjC * _Nullable)initAuthorizeResponse SWIFT_METHOD_FAMILY(none) SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithErrorCode:(NSString * _Nonnull)errorCode errorMessage:(NSString * _Nonnull)errorMessage response:(InitAuthorizeResponseObjC * _Nullable)response OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("InitAuthorizeResponseObjC")
@interface InitAuthorizeResponseObjC : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull authId;
@property (nonatomic, readonly, copy) NSString * _Nonnull authData;
@property (nonatomic, readonly, copy) NSString * _Nonnull authorizeRequestId;
- (nonnull instancetype)initWithAuthId:(NSString * _Nonnull)authId authData:(NSString * _Nonnull)authData authorizeRequestId:(NSString * _Nonnull)authorizeRequestId OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC5SDKCA22InitializeResponseObjC")
@interface InitializeResponseObjC : NSObject
@property (nonatomic, readonly, strong) NSString * _Nonnull error_code;
@property (nonatomic, readonly, strong) NSString * _Nonnull error_message;
- (nonnull instancetype)initWithError_code:(NSString * _Nonnull)error_code error_message:(NSString * _Nonnull)error_message OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class ListAuthorizeResponseObjC;

SWIFT_CLASS_NAMED("ListAuthorizeObjC")
@interface ListAuthorizeObjC : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull errorCode;
@property (nonatomic, readonly, copy) NSString * _Nonnull errorMessage;
@property (nonatomic, readonly, copy) NSArray<ListAuthorizeResponseObjC *> * _Nullable listAuthorize;
- (nonnull instancetype)initWithErrorCode:(NSString * _Nonnull)errorCode errorMessage:(NSString * _Nonnull)errorMessage listAuthorize:(NSArray<ListAuthorizeResponseObjC *> * _Nullable)listAuthorize OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("ListAuthorizeResponseObjC")
@interface ListAuthorizeResponseObjC : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull authorizeRequestId;
@property (nonatomic, readonly, copy) NSString * _Nonnull serial;
@property (nonatomic, readonly) NSInteger quantity;
@property (nonatomic, readonly) NSInteger time;
@property (nonatomic, readonly, copy) NSString * _Nonnull message;
@property (nonatomic, readonly, copy) NSString * _Nonnull initUserInfo;
- (NSString * _Nonnull)initUserInfo SWIFT_METHOD_FAMILY(none) SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly, copy) NSString * _Nonnull initEnvInfo;
- (NSString * _Nonnull)initEnvInfo SWIFT_METHOD_FAMILY(none) SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly, copy) NSString * _Nonnull authId;
@property (nonatomic, readonly, copy) NSString * _Nonnull authData;
@property (nonatomic, readonly, copy) NSString * _Nonnull createTime;
@property (nonatomic, readonly, copy) NSString * _Nonnull expireTime;
/// Hàm khởi tạo dành cho Obj-C
- (nonnull instancetype)initWithAuthorizeRequestId:(NSString * _Nonnull)authorizeRequestId serial:(NSString * _Nonnull)serial quantity:(NSInteger)quantity time:(NSInteger)time message:(NSString * _Nonnull)message initUserInfo:(NSString * _Nonnull)initUserInfo initEnvInfo:(NSString * _Nonnull)initEnvInfo authId:(NSString * _Nonnull)authId authData:(NSString * _Nonnull)authData createTime:(NSString * _Nonnull)createTime expireTime:(NSString * _Nonnull)expireTime OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC5SDKCA13ListCertsObjC")
@interface ListCertsObjC : NSObject
@property (nonatomic, readonly, strong) NSString * _Nonnull error_code;
@property (nonatomic, readonly, strong) NSString * _Nonnull error_message;
/// Mảng certs dưới dạng NSArray<NSDictionary> (mỗi phần tử là 1 cert đã encode)
@property (nonatomic, readonly, strong) NSArray * _Nullable certs;
- (nonnull instancetype)initWithError_code:(NSString * _Nonnull)error_code error_message:(NSString * _Nonnull)error_message certs:(NSArray * _Nullable)certs OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC5SDKCA12ListSignObjC")
@interface ListSignObjC : NSObject
@property (nonatomic, readonly, strong) NSString * _Nonnull error_code;
@property (nonatomic, readonly, strong) NSString * _Nonnull error_message;
@property (nonatomic, readonly, strong) NSArray * _Nullable sign_requests;
- (nonnull instancetype)initWithError_code:(NSString * _Nonnull)error_code error_message:(NSString * _Nonnull)error_message sign_requests:(NSArray * _Nullable)sign_requests OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("RegisterAuthorizeObjC")
@interface RegisterAuthorizeObjC : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull error_code;
@property (nonatomic, readonly, copy) NSString * _Nonnull error_message;
- (nonnull instancetype)initWithErrorCode:(NSString * _Nonnull)errorCode errorMessage:(NSString * _Nonnull)errorMessage OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC5SDKCA18RegisterDeviceObjC")
@interface RegisterDeviceObjC : NSObject
@property (nonatomic, readonly, strong) NSString * _Nonnull error_code;
@property (nonatomic, readonly, strong) NSString * _Nonnull error_message;
- (nonnull instancetype)initWithError_code:(NSString * _Nonnull)error_code error_message:(NSString * _Nonnull)error_message OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC5SDKCA19SessionResponseObjC")
@interface SessionResponseObjC : NSObject
@property (nonatomic, readonly, strong) NSString * _Nonnull error_code;
@property (nonatomic, readonly, strong) NSString * _Nonnull error_message;
@property (nonatomic, readonly, strong) NSString * _Nullable create_time;
@property (nonatomic, readonly, strong) NSString * _Nullable expire_time;
@property (nonatomic, readonly, strong) NSString * _Nullable session_info;
@property (nonatomic, readonly, strong) NSString * _Nullable device_state;
- (nonnull instancetype)initWithError_code:(NSString * _Nonnull)error_code error_message:(NSString * _Nonnull)error_message create_time:(NSString * _Nullable)create_time expire_time:(NSString * _Nullable)expire_time session_info:(NSString * _Nullable)session_info device_state:(NSString * _Nullable)device_state OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC5SDKCA14VerifyCertObjC")
@interface VerifyCertObjC : NSObject
@property (nonatomic, readonly, strong) NSString * _Nonnull error_code;
@property (nonatomic, readonly, strong) NSString * _Nonnull error_message;
- (nonnull instancetype)initWithError_code:(NSString * _Nonnull)error_code error_message:(NSString * _Nonnull)error_message OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
